// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:vuiphim/core/utils/enum.dart';
import 'package:vuiphim/data/hive_database/hive_entities/cast_entity/cast_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/category_entity/category_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/created_entity/created_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/episode_entity/episode_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/genre_entity/genre_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/imdb_entity/imdb_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/kkmovie_movie_entity/kkmovie_movie_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/kkmovie_source_entity/kkmovie_source_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/move_entity/movie_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/movie_detail_entity/movie_detail_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/server_data_entity/server_data_entity.dart';
import 'package:vuiphim/data/hive_database/hive_entities/tmdb_entity/tmdb_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CastEntityAdapter());
    registerAdapter(CategoryEntityAdapter());
    registerAdapter(CreatedEntityAdapter());
    registerAdapter(EpisodeEntityAdapter());
    registerAdapter(GenreEntityAdapter());
    registerAdapter(ImdbEntityAdapter());
    registerAdapter(KkMovieMovieEntityAdapter());
    registerAdapter(KkMovieSourceEntityAdapter());
    registerAdapter(MovieCategoryAdapter());
    registerAdapter(MovieDetailEntityAdapter());
    registerAdapter(MovieEntityAdapter());
    registerAdapter(ServerDataEntityAdapter());
    registerAdapter(TmdbEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CastEntityAdapter());
    registerAdapter(CategoryEntityAdapter());
    registerAdapter(CreatedEntityAdapter());
    registerAdapter(EpisodeEntityAdapter());
    registerAdapter(GenreEntityAdapter());
    registerAdapter(ImdbEntityAdapter());
    registerAdapter(KkMovieMovieEntityAdapter());
    registerAdapter(KkMovieSourceEntityAdapter());
    registerAdapter(MovieCategoryAdapter());
    registerAdapter(MovieDetailEntityAdapter());
    registerAdapter(MovieEntityAdapter());
    registerAdapter(ServerDataEntityAdapter());
    registerAdapter(TmdbEntityAdapter());
  }
}
